Erro ao criar relat√≥rio express: (psycopg2.errors.NotNullViolation) null value in column "observacoes" of relation "relatorios_express" violates not-null constraint DETAIL: Failing row contains (4, EXP2025001, null, 6, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2025-09-01, null, null, null, null, null, sfs, null, sdfsdf, null, null, null, f, null, null, finalizado, null, null, null, 2025-09-01 19:38:07.504955, 2025-09-01 19:38:07.504957, null, Teste, ads, 11111111111, teste@teste.com, teste, 22:22:00, 23:33:00, Chuvoso, 34, null, sdfsfd, 3fsf, 2025-09-01 19:38:07.504455). [SQL: INSERT INTO relatorios_express (numero, empresa_nome, empresa_endereco, empresa_telefone, empresa_email, empresa_responsavel, autor_id, data_visita, periodo_inicio, periodo_fim, condicoes_climaticas, temperatura, checklist_completo, observacoes_gerais, pendencias, recomendacoes, status, latitude, longitude, endereco_visita, created_at, updated_at, finalizado_at) VALUES (%(numero)s, %(empresa_nome)s, %(empresa_endereco)s, %(empresa_telefone)s, %(empresa_email)s, %(empresa_responsavel)s, %(autor_id)s, %(data_visita)s, %(periodo_inicio)s, %(periodo_fim)s, %(condicoes_climaticas)s, %(temperatura)s, %(checklist_completo)s, %(observacoes_gerais)s, %(pendencias)s, %(recomendacoes)s, %(status)s, %(latitude)s, %(longitude)s, %(endereco_visita)s, %(created_at)s, %(updated_at)s, %(finalizado_at)s) RETURNING relatorios_express.id] [parameters: {'numero': 'EXP2025001', 'empresa_nome': 'Teste', 'empresa_endereco': 'ads', 'empresa_telefone': '11111111111', 'empresa_email': 'teste@teste.com', 'empresa_responsavel': 'teste', 'autor_id': 6, 'data_visita': datetime.date(2025, 9, 1), 'periodo_inicio': datetime.time(22, 22), 'periodo_fim': datetime.time(23, 33), 'condicoes_climaticas': 'Chuvoso', 'temperatura': '34', 'checklist_completo': None, 'observacoes_gerais': 'sfs', 'pendencias': 'sdfsfd', 'recomendacoes': 'sdfsdf', 'status': 'finalizado', 'latitude': None, 'longitude': None, 'endereco_visita': '3fsf', 'created_at': datetime.datetime(2025, 9, 1, 19, 38, 7, 504955), 'updated_at': datetime.datetime(2025, 9, 1, 19, 38, 7, 504957), 'finalizado_at': datetime.datetime(2025, 9, 1, 19, 38, 7, 504455)}] (Background on this error at: https://sqlalche.me/e/20/gkpj)